### ISSUE TITLE
glove embedding not used in the code?

### ISSUE THREAD

**Issue by ch3cook-fdu** [heng-hw/SpaCap3D#2]
I've notice that the Transformer Captioner does not use glove embedding as pretrained word embeddings. Would this hurt the captioner's performance?

**Comment by heng-hw** [comment]
Hi @ch3cook-fdu! Thanks for your interest! I've used the glove embedding at some point during the experiments but it did not improve the performance very much. So I did not use it in the later development of the model. You are welcome to add it to see if there is an improvement.

**Comment by ch3cook-fdu** [comment]
Thanks a lot! BTW, could you upload the training log? I found it slow to converge with CIDEr while training, I don't know if this is normal.

**Comment by heng-hw** [comment]
@ch3cook-fdu Yes, it did take some time to converge (the best CIDEr usually appears at epoch 30+). Please see this [log.txt](https://github.com/heng-hw/SpaCap3D/files/8932803/log.txt) for reference. Hope it helps!

**Comment by ch3cook-fdu** [comment]
The cider performance has large fluctuation during training actually 🤔. Thx! That helps a lot!
