### ISSUE TITLE
Evaluation Results

### ISSUE THREAD

**Issue by ch3cook-fdu** [heng-hw/SpaCap3D#3]
I've been evaluating the rgb+normal checkpoints you provided, but the results are low, is it normal?

`python scripts/eval.py --eval_tag 'muleval' --use_color --use_normal --folder 'SPACAP_RGB_NORMAL' --min_iou 0.25 --eval_caption`

[BLEU-1] Mean: 0.6417, Max: 1.0000, Min: 0.0000
[BLEU-2] Mean: 0.5214, Max: 1.0000, Min: 0.0000
[BLEU-3] Mean: 0.4093, Max: 1.0000, Min: 0.0000
[BLEU-4] Mean: 0.3211, Max: 1.0000, Min: 0.0000
[CIDEr] Mean: 0.5393, Max: 7.1255, Min: 0.0000
[ROUGE-L] Mean: 0.5268, Max: 1.0000, Min: 0.1015
[METEOR] Mean: 0.2585, Max: 1.0000, Min: 0.0448

But that of multiview+normal are pretty high:

`python scripts/eval.py --eval_tag 'muleval' --use_multiview --use_normal --folder 'SPACAP_MV_NORMAL' --min_iou 0.25 --eval_caption`

[BLEU-1] Mean: 0.6688, Max: 1.0000, Min: 0.0000
[BLEU-2] Mean: 0.5604, Max: 1.0000, Min: 0.0000
[BLEU-3] Mean: 0.4541, Max: 1.0000, Min: 0.0000
[BLEU-4] Mean: 0.3665, Max: 1.0000, Min: 0.0000
[CIDEr] Mean: 0.6350, Max: 5.0265, Min: 0.0000
[ROUGE-L] Mean: 0.5601, Max: 1.0000, Min: 0.1015
[METEOR] Mean: 0.2684, Max: 1.0000, Min: 0.0448

**Comment by heng-hw** [comment]
Hi @ch3cook-fdu! It is normal. For me, the evaluation results for `rgb+normal` when min_iou=0.25 is:

[BLEU-1] Mean: 0.6444, Max: 1.0000, Min: 0.0000
[BLEU-2] Mean: 0.5387, Max: 1.0000, Min: 0.0000
[BLEU-3] Mean: 0.4373, Max: 1.0000, Min: 0.0000
[BLEU-4] Mean: 0.3530, Max: 1.0000, Min: 0.0000
[CIDEr] Mean: 0.5806, Max: 10.0000, Min: 0.0000
[ROUGE-L] Mean: 0.5503, Max: 1.0000, Min: 0.1015
[METEOR] Mean: 0.2616, Max: 1.0000, Min: 0.0448

and for `multiview+normal` is:

[BLEU-1] Mean: 0.6684, Max: 1.0000, Min: 0.0000
[BLEU-2] Mean: 0.5598, Max: 1.0000, Min: 0.0000
[BLEU-3] Mean: 0.4528, Max: 1.0000, Min: 0.0000
[BLEU-4] Mean: 0.3646, Max: 1.0000, Min: 0.0000
[CIDEr] Mean: 0.6330, Max: 5.0265, Min: 0.0000
[ROUGE-L] Mean: 0.5571, Max: 1.0000, Min: 0.1015
[METEOR] Mean: 0.2671, Max: 1.0000, Min: 0.0478

There is some oscillation in the evaluation. You can try with different seeds by setting `--seed` to see the results could be relatively better or worse. If you want to get more fair results, you can toggle on the flag `--mul_eval ` to evaluate with 100 different seeds and look at the average. 

Hope it helps!

**Comment by ch3cook-fdu** [comment]
Thanks! That helps a lot!
